apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: guestbook-simple-prod

images:
- name: ghcr.io/zvercodebender/guestbook
  newName: ghcr.io/zvercodebender/guestbook
  newTag: v0.0.1

patchesStrategicMerge:
- replica-patch.yaml
